name: CI

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository
  pull_request:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  build_django_42:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        django-version: [4.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install specific Django version
      run: pip install Django==${{ matrix.django-version }}

    - name: Run tests
      run: |
        python manage.py test

    - name: Build distribution package
      run: python setup.py sdist

    - name: Archive distribution package
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.gz

  build_django_50:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
        django-version: [5.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install specific Django version
      run: pip install Django==${{ matrix.django-version }}

    - name: Run tests
      run: |
        python manage.py test

    - name: Build distribution package
      run: python setup.py sdist

    - name: Archive distribution package
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.gz
